### ISSUE TITLE
Changes with 5.10?

### ISSUE THREAD

**Issue by simonschmeisser** [sailfish-on-dontbeevil/realtek-bt-firmware#1]
bluetooth didn't work for me (couldn't enable in ui). when looking at `dmesg` I noticed:
```
[    8.826625] Bluetooth: hci0: RTL: examining hci_ver=07 hci_rev=000b lmp_ver=07 lmp_subver=8703
[    8.830835] Bluetooth: hci0: RTL: chip_type status=0 type=5
[    8.834965] Bluetooth: hci0: RTL: rom_version status=0 version=1
[    8.834989] Bluetooth: hci0: RTL: loading rtl_bt/rtl8723cs_xx_fw.bin
[    8.850225] Bluetooth: hci0: RTL: loading rtl_bt/rtl8723cs_xx_config-pinephone.bin
[    8.850316] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723cs_xx_config-pinephone.bin failed with error -2
[    8.850323] Bluetooth: hci0: RTL: mandatory config file rtl_bt/rtl8723cs_xx_config not found

```

some sources claim that renaming/symlinking the `rtl_bt/rtl8723cs_xx_config-pinebook.bin` to `rtl_bt/rtl8723cs_xx_config-pinephone.bin` should do the trick. I can confirm that doing this removes the warning and I can pair the bluetooth with my notebook. The connection drops quickly however so I'm not sure if that is really the intended solution

I could not find a -pinephone.bin in other distributions but they typically use older kernels

**Comment by piggz** [comment]
I was under the impression they dropped the suffix's .... in any case, BT isnt working at all for me in the current kernel, but im building the new rc2 5.10 kernel, which i think has some BT fixes.  Will test shortly.

**Comment by simonschmeisser** [comment]
apparently megi has his own naming scheme? https://megous.com/git/linux-firmware/tree/rtl_bt

```
[    6.368779] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[    6.368802] cfg80211: failed to load regulatory.db
```
that file can also be found there 

Edit: it's for the wireless
